[package]
name = "hyprctl-custom"
version = "0.2.0"
edition = "2021"

[dependencies]
clap = { version = "4.3", features = ["derive"] }
hyprland = "0.3"

[profile.release]
strip = "debuginfo"
lto = true
codegen-units = 1
