
name: Build
on:
  push:
    branches:
      - main
    tags:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        target:
        - aarch64-unknown-linux-gnu
        - x86_64-unknown-linux-gnu
    steps:
    - uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: 1.80.1
        targets: ${{ matrix.target }}

    - name: Build
      uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target ${{ matrix.target }} --release

    - name: Create archive
      run: |
        tar \
          -C target/${{ matrix.target }}/release \
          -czvf hyprctl-custom-$(date -u +"%Y%m%d-%H%M%SUTC")-$(git rev-parse --short HEAD)-${{ matrix.target }}.tar.gz \
          hyprctl-custom

    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        path: hyprctl-custom-*.tar.gz
        if-no-files-found: error

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build]
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v3

    - name: Release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: artifact/*.tar.gz

